### ISSUE TITLE
great project

### ISSUE THREAD

**Issue by NeuerUser** [ZipCPU/arrowzip#1]
I also got this board to learn about FPGA. It would be too great to also have the ZipCPU on this board.
But it looks very daunting to me. Do you think you can get it working?

Cheers

Michael

**Comment by ZipCPU** [comment]
Yes.

Large portions of the design are working already, and should be checked in.

I'm still testing the flash memory using my new flash driver, but haven't (yet) gotten to either the SDRAM or the SPI-based accelerometer..  Those remain on my to-do list.  The CPU should be able to work as is though.

Still need to figure out how to package the various Altera/Intel specific primitives.  Those are likely to slow you down.

**Comment by NeuerUser** [comment]
Hi Dan

That sounds like pretty good news. I would love to play around with it. Looking forward to anything you release.

Thanks again for your hard work!

Michael

**Comment by ZipCPU** [comment]
I threw in the two altera primitives, so feel free to try out the project with them.

I still don't have the SDRAM memory working (yet), but the CPU should be in working order.

Dan

**Comment by NeuerUser** [comment]
Thanks. That helps a lot. 
SDRAM would be nice, but it  would alrady be great to get it working even without. I will see if I can get it compiled and running on the board. It is such a nice, small and inexpensive board.

**Comment by ZipCPU** [comment]
The good news is that I already have the [SDRAM controller](https://github.com/ZipCPU/xulalx25soc/blob/master/rtl/wbsdram.v), I just need to port it from [another one of my designs](https://github.com/ZipCPU/xulalx25soc) to this one and get it up and running.

**Comment by NeuerUser** [comment]
That's very nice, indeed. That would mean it could be a fully featured Soc .)

**Comment by ZipCPU** [comment]
The ZipCPU now works on this board.  I still need to get the SDRAM and MEMs sensor running, but the CPU itself is running.

To use, load the design onto your board, and then run (from sw/host) "zipload -r ../board/cputest".  While it is loading, telnet into port 6956 (one greater than FPGAPORT in sw/host/port.h).  Once the zipload program has loaded the CPU test program into the flash, you'll see a report in your telnet window.
