### ISSUE TITLE
dumpflash not working

### ISSUE THREAD

**Issue by NeuerUser** [ZipCPU/arrowzip#8]
Before this test I had run "hello", so that the flash got successfully written to.
~~~~
 ./wbregs version
00600014 ( VERSION) : [....] 20190309
$ ./wbregs buildtime
00600000 (BUILDTIME) : [..GC] 00114743
$ time ./dumpflash 
Before starting, nread = 0
VERSION: 20190309

READ-COMPLETE
The read was accomplished in 19 bytes over the UART

real    0m0.019s
user    0m0.000s
sys     0m0.013s
~~~~
The file is 8MB large, but contains only zeros.

**Comment by ZipCPU** [comment]
Try a git pull.  I had that problem with an earlier version, and everything is working properly for me now.

**Comment by NeuerUser** [comment]
I am on commit b9509a2f8ba3b568af51939232b86f58773a00c1 (so, only the port.h commit missing). I rebuilt all programs via "make clean" and "make" in the sw/host directory. Same result.

**Comment by ZipCPU** [comment]
Ok, I see the bug here ... I was chasing down a bus error some time ago (never found it) in dumpflash, and so I had modified the code so that it would look only at the end of the flash.

I just pushed a working version of dumpflash.cpp to the repo.  Let me know if that works for you.

**Comment by NeuerUser** [comment]
Yes, seems to work now. (but taking ages, of course, so I probably will cancel the transfer before it is finished...)

**Comment by ZipCPU** [comment]
Yes to taking ages.  I think I left it running for about 10 hrs before it finally got to the end.

**Comment by ZipCPU** [comment]
Also ... the vector read is about 3x faster, but I turned that off in case you wanted to interrupt it mid-way.  I might go back to vector reads, but instead to doing them in chunks so that you can interrupt it and get the results, while also having it run 3x as fast.
